#! /bin/sh
# Startup script for the nginx Web Server
# chkconfig: - 85 15
# description: nginx is a World Wide Web server. It is used to serve
# HTML files and CGI.
# processname: nginx
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="nginx daemon"
NAME=nginx
IN_DIR="/www/lanmps"
DAEMON=$IN_DIR/nginx/sbin/$NAME
CONF=$IN_DIR/nginx/conf/$NAME.conf
PID_FILE=/usr/local/var/run/nginx.pid
SCRIPT_NAME=$IN_DIR/action/$NAME
IN_WEB_LOG_DIR="/www/wwwLogs"

case "$1" in
 start)
 echo -n "Starting $DESC: $NAME"
 nginx
 echo "."
 ;;
 stop)
 echo -n "Stopping $DESC: $NAME"
 nginx -s stop
 echo "."
 ;;
 test)
 echo -n "Stopping $DESC: $NAME"
 nginx -t
 echo "."
 ;;
 reload|graceful)
 echo -n "Reloading $DESC configuration..."
 nginx -s reload
 echo "."
 ;;
 restart)
 echo -n "Restarting $DESC: $NAME"
 nginx -s stop
 nginx -s start
 echo "."
 ;;
 status)
	if [ -f $PID_FILE ]; then
		echo "Nginx is runing!"
    else
		echo "Nginx is stop!"
    fi
 ;;
 *)
 echo "Usage: $SCRIPT_NAME {start|stop|reload|restart|status|test} " >&2
 exit 3
 ;;
esac

exit 0
